### ISSUE TITLE
Bug: React native possibly restarts when inserting SIM card

### ISSUE THREAD

**Issue by robbederks** [commaai/openpilot-apks#37]
Same fix as in: https://github.com/commaai/android_packages_apps_NEOSSetup/commit/0ac4e57e73df87d91b43c0eeb5f19217da8cbff9

**Comment by andyh2** [comment]
Offroad isn’t affected https://github.com/commaai/openpilot-apks/blob/master/offroad/android/app/src/main/AndroidManifest.xml#L24
