### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by TianLiJun** [commaai/openpilot-apks#5]
I have set up an VM with ubuntu 16.04.6 installed, following the README.md instruction and I'm getting execution error:
`2 actionable tasks: 2 executed`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (28, 34): Unresolved reference: Log`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (29, 34): Unresolved reference: Log`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (65, 23): Unresolved reference: ControlState`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (201, 28): Cannot access class 'Log.Event.Builder'. Check your module classpath for missing or conflicting dependencies`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (201, 33): Unresolved reference: initUiLayoutState`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (227, 38): Unresolved reference: CLog`
`e: /home/tian/work/openpilot/openpilot-apks/frame/app/src/main/java/ai/comma/plus/frame/MainActivity.kt: (298, 38): Unresolved reference: CLog
`

**Comment by geohot** [comment]
I think this is the same as #2
